name: smartcharge_v2
description: "A new Flutter project."
version: 1.0.0+1

environment:
  sdk: ^3.10.8

dependencies:
  flutter:
    sdk: flutter
  
  # UI
  google_fonts: ^6.1.0
  cupertino_icons: ^1.0.8
  
  # Utility
  provider: ^6.1.1
  intl: ^0.19.0
  shared_preferences: ^2.5.4
  
  # Grafici e PDF
  fl_chart: ^0.66.0
  pdf: ^3.10.8
  printing: ^5.11.1
  path_provider: ^2.1.2
  share_plus: ^7.2.0
  universal_html: ^2.2.4
  
  # Firebase
  firebase_core: ^3.15.0
  cloud_firestore: ^5.6.5
  firebase_auth: ^5.5.2
  
  # Effetti
  fluid_background: ^1.0.5
  
  # ðŸ”¥ NOTIFICHE
  flutter_local_notifications: ^17.1.0
  timezone: ^0.9.2
  permission_handler: ^11.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/logo.png"
  adaptive_icon_background: "#000000"
  adaptive_icon_foreground: "assets/images/logo_foreground.png"
  remove_alpha_ios: true

flutter:
  uses-material-design: true
  
  # ðŸ”¥ FONT
  fonts:
    - family: CourierNew
      fonts:
        - asset: fonts/Courier New.ttf
  
  # ðŸ”¥ ASSETS
  assets:
    - assets/cars.json
    - assets/images/logo.png
    - assets/images/logo_foreground.png