name: smartcharge_v2
description: "A new Flutter project for Smart EV Charging."
version: 1.0.0+1

environment:
  sdk: ^3.10.8

dependencies:
  flutter:
    sdk: flutter
  
  # UI & Fonts
  google_fonts: ^6.1.0
  cupertino_icons: ^1.0.8
  flutter_dotenv: ^5.2.1
  
  # State Management & Storage
  provider: ^6.1.1
  shared_preferences: ^2.5.4
  intl: ^0.19.0
  image_picker: ^1.0.4
  
  # AI & FILE PICKER
  google_generative_ai: ^0.4.0
  file_picker: ^8.0.0
  
  # ESTRAZIONE PDF
  syncfusion_flutter_pdf: ^24.2.3
  
  # Grafici e PDF
  fl_chart: ^0.66.0
  pdf: ^3.10.8
  printing: ^5.11.1
  path_provider: ^2.1.2
  share_plus: ^7.2.0
  universal_html: ^2.3.0
  
  # Firebase
  firebase_core: ^3.15.0
  cloud_firestore: ^5.6.5
  firebase_auth: ^5.5.2
  
  # Effetti Visivi
  fluid_background: ^1.0.5
  
  # Notifiche & Permessi
  flutter_local_notifications: ^17.1.0
  timezone: ^0.9.2
  permission_handler: ^11.3.0

dev_dependencies:
  google_sign_in: ^6.1.5
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/logo.png"
  adaptive_icon_background: "#000000"
  adaptive_icon_foreground: "assets/images/logo_foreground.png"
  remove_alpha_ios: true

flutter:
  uses-material-design: true
  
  fonts:
    - family: CourierNew
      fonts:
        - asset: fonts/Courier New.ttf
  
  assets:
    - assets/cars.json
    - assets/images/logo.png
    - assets/images/logo_foreground.png
    # .env Ã¨ stato rimosso dagli asset